- name: Set authorized key for user pi copying it from current user
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
- name: Make sure ssh service is configured to start on boot
  systemd:
    name: ssh
    enabled: true
    state: started
